- name: delete ip_rsa user1
  file:
    path: roles/addusers/files/ssh-keys-user1/id_rsa
    state: absent

- name: delete ip_rsa user1
  file:
    path: roles/addusers/files/ssh-keys-user2/id_rsa
    state: absent

- name: ensure SSH key is generated
  command: ssh-keygen -t rsa -f roles/addusers/files/ssh-keys-user1/id_rsa -N ''

- name: ensure SSH key is generated
  command: ssh-keygen -t rsa -f roles/addusers/files/ssh-keys-user2/id_rsa -N ''
