---
- name: install Apache httpd
  hosts: webservers
  become: true

  tasks:
  - name: install Apache httpd
    yum: name=httpd state=latest

  - name: start Apache httpd service
    service: name=httpd state=started
