---
- name: install Apache httpd
  hosts: webservers
  become: true

  tasks:

  - name: start Apache httpd service
    service: name=httpd state=stopped

  - name: install Apache httpd
    yum: name=httpd state=absent
